import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import Script from "next/script";
import ProgressBarProvider from "@/components/progress-bar";

export const metadata: Metadata = {
	title: "Dashboard Shadnc Template",
	description: "Generated by create next app",
	// themeColor: "#ffffff",
	// viewport: { width: "device-width", initialScale: 1, maximumScale: 1 },
	keywords: "react,shadcn,kit,application,dashboard,admin,template",
	icons: [
		{
			rel: "shortcut icon",
			url: "/meta/favicon.ico",
		},
		{
			rel: "apple-touch-icon",
			sizes: "180x180",
			url: "/meta/apple-touch-icon.png",
		},
		{
			sizes: "32x32",
			url: "/meta/favicon-32x32.png",
			type: "image/png",
		},
		{
			sizes: "16x16",
			url: "/meta/favicon-16x16.png",
			type: "image/png",
		},
		{
			rel: "manifest",
			url: "/meta/site.webmanifest",
		},
	],
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth" suppressHydrationWarning>
			<body className={GeistSans.className}>
				<Script id="color-presets" strategy="beforeInteractive">
					{`(function() {const preset = JSON.parse(localStorage.getItem("settings"))?.state?.themeColorPresets; if (preset){document.documentElement.setAttribute("data-theme", preset);}})();`}
				</Script>
				<ProgressBarProvider>
					<ThemeProvider attribute="class">{children}</ThemeProvider>
				</ProgressBarProvider>
			</body>
		</html>
	);
}
